 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ["build",
      "-t","gcr.io/$PROJECT_ID/labci-awsgui:$COMMIT_SHA",
      "--build-arg", "REACT_APP_APIHOST=https://cloudrun-api-gssmt3brqq-ew.a.run.app/",
      "--build-arg", "REACT_APP_STOPPEDVMIMG=${_PIC2}",
      "--build-arg", "REACT_APP_STARTEDVMIMG=${_PIC1}",
#      "--build-arg", "REACT_APP_STOPPEDVMIMG=https://storage.googleapis.com/aws-gui-0705545/destroy",
#      "--build-arg", "REACT_APP_STARTEDVMIMG=https://storage.googleapis.com/aws-gui-0705545/off",  
      "."] 
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/labci-awsgui:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'cld-srv'
   - '--image'
   - 'gcr.io/$PROJECT_ID/labci-awsgui:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
 images:
 - 'gcr.io/$PROJECT_ID/labci-awsgui:$COMMIT_SHA'